name: weekly_session_environment

channels: 
    - conda-forge

dependencies:
    - python=3.7
    - tensorflow=2.5.0
    - matplotlib
    - numpy
    - pandas
    - scikit-learn 
    - pydot
    - graphviz
    - opencv
